#!/bin/bash
filepath=$(cd "$(dirname "$0")"; pwd)
source $filepath/ss.func.sh
file=`check $1 $2`
n=$?
if [ "$n" != "0" ];then
	echo $file
	exit
fi

j=`conf $file`
act=`act $1`
case $act in
	"1") t $j ;;
	"2") p ;;
	"3") s $j ;;
	"4") h ;;
esac
